blueprint:
  name: "AWTRIX DPC Alert - Test Notification 🧪"
  description:
    "Sends a test notification to AWTRIX devices to verify DPC alert configuration.\n\n
    This blueprint creates a manually-triggered automation for testing alert displays
    before real DPC alerts arrive. Essential for validating your setup.\n\n
    ## 🎯 Purpose\n\n
    - Verify icons are correctly uploaded and display properly\n\n
    - Test different criticality levels (1-4) with accurate colors and effects\n\n
    - Validate sound notifications at different thresholds\n\n
    - Test both Custom App (persistent) and Notification (temporary) display modes\n\n
    - Confirm rainbow text effects work as configured\n\n
    - Ensure MQTT communication is functioning correctly\n\n\n
    ## 📝 How to Use\n\n
    1. Create automation from this blueprint\n\n
    2. Select your AWTRIX device(s)\n\n
    3. Choose a test criticality level (1-4)\n\n
    4. Configure durations, effects, and display mode\n\n
    5. Save and trigger manually to send test notification\n\n
    6. Verify display, colors, icons, sound, and effects\n\n
    7. Adjust settings as needed and test again\n\n\n
    ## ✨ Features\n\n
    - Test all 4 criticality levels with proper color coding\n\n
    - Configurable rainbow text effect (minimum level threshold)\n\n
    - Choose display mode: Custom App, Notification, or Both\n\n
    - Separate durations for custom apps and notifications\n\n
    - Hold mode support (notification duration = 0)\n\n
    - Optional sound notifications\n\n
    - Test payload visible in trace for debugging"
  domain: automation
  input:
    awtrix:
      name: AWTRIX Device
      description: Select the AWTRIX devices for testing
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

    test_level:
      name: Test Level
      description: |
        Select the criticality level to test:
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 1
          max: 4
          mode: box
          step: 1
      default: 3

    message_duration:
      name: Message Duration ⏱️
      description: How long the message should remain on screen (in seconds)
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 20

    notification_duration:
      name: Notification Duration 🔔
      description: How long the notification should remain visible (0 = hold until dismissed)
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 0

    icon_test:
      name: Test Icon
      description: Icon filename to display in the test (without extension)
      selector:
        text: {}
      default: "dpc-warning"

    enable_sound:
      name: Test with Sound 🔊
      description: Play a sound with the test notification
      selector:
        boolean: {}
      default: false

    sound_file:
      name: Sound File
      description: Audio file name to play (without extension)
      selector:
        text: {}
      default: "alarm"

    rainbow_level:
      name: Minimum Level for Rainbow 🌈
      description: |
        Display rainbow text for alerts of this level or higher (0 = disabled):
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    display_mode:
      name: Display Mode 📺
      description: |
        Choose how to display the test on AWTRIX:
        - Custom App: Persistent display until cleared
        - Notification: Temporary pop-up that auto-dismisses
        - Both: Send both custom app and notification
      selector:
        select:
          options:
            - label: "Custom App (Persistent)"
              value: "app"
            - label: "Notification (Temporary)"
              value: "notification"
            - label: "Both"
              value: "both"
      default: "notification"

mode: single

variables:
  device_ids: !input awtrix
  app_topic: "dpc_alert"
  test_level: !input test_level
  message_duration: !input message_duration
  notification_duration: !input notification_duration
  icon_test: !input icon_test
  enable_sound: !input enable_sound
  sound_file: !input sound_file
  rainbow_level: !input rainbow_level
  display_mode: !input display_mode

  devices_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/custom/' ~ app_topic] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  notify_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/notify'] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  color_map:
    0: "#0080FF"
    1: "#00FF00"
    2: "#FFFF00"
    3: "#FF6000"
    4: "#FF0000"

  level_names:
    1: "Ordinaria"
    2: "Moderata"
    3: "Elevata"
    4: "Estrema"

  test_payload: |
    {%- set is_notification = display_mode in ['notification', 'both'] %}
    {%- set duration_value = notification_duration if is_notification else message_duration %}
    
    {%- set alert_obj = {
      'text': 'TEST DPC Alert - Livello ' ~ level_names[test_level],
      'icon': icon_test,
      'stack': false
    } %}
    
    {#- Only set color if rainbow is not active -#}
    {%- if rainbow_level == 0 or test_level < rainbow_level %}
      {%- set alert_obj = dict(alert_obj, color=color_map[test_level]) %}
    {%- endif %}
    
    {%- if rainbow_level > 0 and test_level >= rainbow_level %}
      {%- set alert_obj = dict(alert_obj, rainbow=true) %}
    {%- endif %}
    
    {%- if duration_value > 0 %}
      {%- set alert_obj = dict(alert_obj, duration=duration_value) %}
    {%- endif %}
    
    {%- if enable_sound %}
      {%- set alert_obj = dict(alert_obj, sound=sound_file) %}
    {%- endif %}
    
    {%- if is_notification and notification_duration == 0 %}
      {%- set alert_obj = dict(alert_obj, hold=true) %}
    {%- endif %}
    
    {{ alert_obj|tojson }}

trigger: []

condition: []

action:
  # Send to custom app if mode is 'app' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['app', 'both'] }}"
    then:
      - repeat:
          for_each: "{{ devices_topics }}"
          sequence:
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: "{{ test_payload }}"

  # Send AWTRIX notification if mode is 'notification' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['notification', 'both'] }}"
    then:
      - repeat:
          for_each: "{{ notify_topics }}"
          sequence:
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: "{{ test_payload }}"

  - service: system_log.write
    data:
      message: "DPC Alert test notification sent to {{ devices_topics|length }} AWTRIX device(s) - Level {{ test_level }} - Mode: {{ display_mode }}"
      level: info
