blueprint:
  name: "AWTRIX Civil Protection Alert ðŸ‡®ðŸ‡¹"
  description:
    "Display Italian Civil Protection (Protezione Civile) weather alerts on your AWTRIX LED matrix device.\n\n
    Automatically monitors DPC alert sensors and displays color-coded notifications with icons,
    sound alerts, and visual effects based on criticality level.\n\n
    ## âš ï¸ REQUIREMENTS\n
    - **Home Assistant** 2024.6.0 or newer\n
    - **AWTRIX 3** device configured with MQTT\n
    - **[DPC Alert Integration](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert)** installed and configured\n\n
    ## ðŸŽ¯ KEY FEATURES\n
    - **Multi-sensor monitoring**: Track multiple DPC sensors simultaneously\n
    - **Criticality filtering**: Show only alerts above configurable threshold (0-4)\n
    - **Automatic color coding**: Vivid colors based on alert level (Blue/Green/Yellow/Orange/Red)\n
    - **Compact display format**: Shows abbreviated alerts (e.g. \"IDR3-TMP4\") for both apps and notifications\n
    - **Rainbow text effect**: Optional colorful animation for high-severity alerts\n
    - **Sound notifications**: Optional audio alerts with minimum level threshold\n
    - **Flexible display modes**: Choose Custom App (persistent), Notification (temporary), or Both\n
    - **Auto-clear**: Removes alerts automatically when no longer active\n
    - **Multi-device support**: Send to multiple AWTRIX devices simultaneously\n
    - **Test mode**: Manually trigger test alerts without waiting for real DPC data\n\n
    ## ðŸ“º DISPLAY FORMAT\n
    Both Custom App and Notification use compact format: **IDR3-TMP4** (all alerts on one screen)\n
    - **IDR** = Rischio Idraulico (Hydraulic)\n
    - **TMP** = Rischio Temporali (Storm)\n
    - **IDG** = Rischio Idrogeologico (Hydrogeological)\n
    - Number = criticality level (1-4)\n
    Color is based on highest alert level present.\n\n
    ## ðŸ“¦ RECOMMENDED ICONS\n
    Upload these icons to your AWTRIX for best results:\n
    - `dpc-idraulico` (63) - Hydraulic risk (floods, overflows)\n
    - `dpc-temporali` (49299) - Thunderstorm risk (lightning, strong winds)\n
    - `dpc-idrogeologico` (42639) - Hydrogeological risk (landslides, mudflows)\n
    - `dpc-warning` (16754) - Generic alert icon (fallback)\n\n
    Get icons from [LaMetric Icons](https://developer.lametric.com/icons) or create custom GIF files.\n
    See [Icons Upload Guide](https://github.com/Raythekool/ha-awtrix-dpc-alert/blob/main/ICONS_UPLOAD.md) for automated upload script.\n\n
    ## âš™ï¸ CONFIGURATION OPTIONS\n
    - **Alert Level Threshold**: Filter by minimum criticality (0-4)\n
    - **Display Durations**: Separate controls for custom apps and notifications\n
    - **Rainbow Text Level**: Enable rainbow animation at specified level (0=disabled)\n
    - **Sound Settings**: Optional audio with minimum level threshold\n
    - **Display Mode**: Custom App (stays visible), Notification (temporary pop-up), or Both\n
    - **Custom Icons**: Override default icon names for each risk type\n
    - **Test Mode**: Enable manual testing with configurable alert levels\n\n
    ## ðŸ”— MORE INFO\n
    Documentation: https://github.com/Raythekool/ha-awtrix-dpc-alert\n
    Updates: https://github.com/Raythekool/ha-awtrix-dpc-alert/blob/main/awtrix_dpc_alert.yaml"
  domain: automation
  homeassistant:
    min_version: "2024.6.0"
  source_url: https://github.com/Raythekool/awtrix_dpc_alert/blob/main/awtrix_dpc_alert.yaml
  input:
    awtrix:
      name: AWTRIX Device
      description: Select your AWTRIX device
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

    dpc_sensors:
      name: DPC Alert Sensors
      description: Select the alert sensors you want to monitor
      selector:
        entity:
          filter:
            - domain: binary_sensor
              integration: dpc
          multiple: true

    warning_level:
      name: Minimum Alert Level
      description: |
        0 = Show all alerts (including no criticality)
        1 = Green (Ordinary criticality)
        2 = Yellow (Moderate criticality)
        3 = Orange (High criticality)
        4 = Red (Extreme criticality)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 1

    message_duration:
      name: Message Duration â±ï¸
      description: How long the message should stay on screen (in seconds). 0 = use global time
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 20

    notification_duration:
      name: Notification Duration ðŸ””
      description: How long the notification should remain visible (0 = hold until manual dismissal)
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 10

    icon_idraulico:
      name: Hydraulic Risk Icon
      description: "Icon for hydraulic risk (floods, overflows).\n
        Filename: dpc-idraulico (LaMetric ID: 63)"
      selector:
        text: {}
      default: "dpc-idraulico"

    icon_temporali:
      name: Storm Risk Icon
      description: "Icon for storm risk.\n
        Filename: dpc-temporali (LaMetric ID: 49299)"
      selector:
        text: {}
      default: "dpc-temporali"

    icon_idrogeologico:
      name: Hydrogeological Risk Icon
      description: "Icon for hydrogeological risk (landslides, mudslides).\n
        Filename: dpc-idrogeologico (LaMetric ID: 42639)"
      selector:
        text: {}
      default: "dpc-idrogeologico"

    icon_warning:
      name: Generic Alert Icon
      description: "Generic icon for other alert types.\n
        Filename: dpc-warning (LaMetric ID: 16754)"
      selector:
        text: {}
      default: "dpc-warning"

    enable_sound:
      name: Enable Sound ðŸ”Š
      description: Play a sound when an alert arrives
      selector:
        boolean: {}
      default: false

    sound_level:
      name: Minimum Level for Sound
      description: |
        Play sound only for alerts of this level or higher:
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 1
          max: 4
          mode: box
          step: 1
      default: 3

    sound_file:
      name: Sound File
      description: |
        Name of the audio file to play (without extension).
        Examples: alarm, doorbell, notification, etc.
        See the AWTRIX documentation for available sounds.
      selector:
        text: {}
      default: "alarm"

    rainbow_level:
      name: Minimum Level for Rainbow ðŸŒˆ
      description: |
        Display rainbow text for alerts of this level or higher (0 = disabled):
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    display_mode:
      name: Display Mode ðŸ“º
      description: |
        Choose how to display alerts on AWTRIX:
        - Custom App: Persistent compact display (e.g. "IDR3-TMP4")
        - Notification: Temporary compact pop-up (e.g. "IDR3-TMP4")
        - Both: Persistent app + temporary notification
      selector:
        select:
          options:
            - label: "Custom App (Persistent)"
              value: "app"
            - label: "Notification (Temporary)"
              value: "notification"
            - label: "Both"
              value: "both"
      default: "app"

    # TEST MODE INPUTS
    enable_test_mode:
      name: Enable Test Mode ðŸ§ª
      description: |
        Enable test mode to manually trigger alerts.
        When enabled, automation ignores DPC sensors and uses test levels instead.
        Perfect for verifying icons, colors, and display settings.
      selector:
        boolean: {}
      default: false

    test_level_idraulico:
      name: "[TEST] Hydraulic Risk Level ðŸŒŠ"
      description: "Test level for hydraulic risk (0 = disabled, 1-4 = criticality)"
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    test_level_temporali:
      name: "[TEST] Storm Risk Level âš¡"
      description: "Test level for storm risk (0 = disabled, 1-4 = criticality)"
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    test_level_idrogeologico:
      name: "[TEST] Hydrogeological Risk Level ðŸ”ï¸"
      description: "Test level for hydrogeological risk (0 = disabled, 1-4 = criticality)"
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

mode: restart

variables:
  device_ids: !input awtrix
  app_topic: "dpc_alert"
  devices_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/custom/' ~ app_topic] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  notify_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/notify'] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  dpc_sensors: !input dpc_sensors
  warning_level: !input warning_level
  message_duration: !input message_duration
  notification_duration: !input notification_duration
  icon_idraulico: !input icon_idraulico
  icon_temporali: !input icon_temporali
  icon_idrogeologico: !input icon_idrogeologico
  icon_warning: !input icon_warning
  enable_sound: !input enable_sound
  sound_level: !input sound_level
  sound_file: !input sound_file
  rainbow_level: !input rainbow_level
  display_mode: !input display_mode
  enable_test_mode: !input enable_test_mode
  test_level_idraulico: !input test_level_idraulico
  test_level_temporali: !input test_level_temporali
  test_level_idrogeologico: !input test_level_idrogeologico

  # Color map for criticality levels
  color_map:
    0: "#0080FF"
    1: "#00FF00"
    2: "#FFFF00"
    3: "#FF6000"
    4: "#FF0000"

  # Criticality level names
  level_names:
    0: "None"
    1: "Ordinaria"
    2: "Moderata"
    3: "Elevata"
    4: "Estrema"

  # Risk abbreviations for compact display
  risk_abbr:
    idraulico: "IDR"
    temporali: "TMP"
    idrogeologico: "IDG"

  # Unified compact payload for both app and notification
  compact_payload: |
    {%- set ns = namespace(parts=[], max_level=0, first_icon='') %}
    
    {%- if enable_test_mode %}
      {# TEST MODE: Use test levels #}
      {%- if test_level_idraulico > 0 %}
        {%- set ns.parts = ns.parts + ['IDR' ~ test_level_idraulico|string] %}
        {%- if test_level_idraulico > ns.max_level %}
          {%- set ns.max_level = test_level_idraulico %}
        {%- endif %}
        {%- if ns.first_icon == '' %}
          {%- set ns.first_icon = icon_idraulico %}
        {%- endif %}
      {%- endif %}
      
      {%- if test_level_temporali > 0 %}
        {%- set ns.parts = ns.parts + ['TMP' ~ test_level_temporali|string] %}
        {%- if test_level_temporali > ns.max_level %}
          {%- set ns.max_level = test_level_temporali %}
        {%- endif %}
        {%- if ns.first_icon == '' %}
          {%- set ns.first_icon = icon_temporali %}
        {%- endif %}
      {%- endif %}
      
      {%- if test_level_idrogeologico > 0 %}
        {%- set ns.parts = ns.parts + ['IDG' ~ test_level_idrogeologico|string] %}
        {%- if test_level_idrogeologico > ns.max_level %}
          {%- set ns.max_level = test_level_idrogeologico %}
        {%- endif %}
        {%- if ns.first_icon == '' %}
          {%- set ns.first_icon = icon_idrogeologico %}
        {%- endif %}
      {%- endif %}
    {%- else %}
      {# REAL MODE: Use DPC sensors #}
      {%- for sensor in dpc_sensors %}
        {%- if is_state(sensor, 'on') and state_attr(sensor, 'level')|int(0) >= warning_level %}
          {%- set level = state_attr(sensor, 'level')|int(0) %}
          {%- set risk = state_attr(sensor, 'risk') %}
          
          {%- set icon = icon_warning %}
          {%- set risk_type = 'warning' %}
          {%- set abbr = 'ALL' %}
          
          {%- if 'idraulico' in risk|lower %}
            {%- set icon = icon_idraulico %}
            {%- set risk_type = 'idraulico' %}
            {%- set abbr = 'IDR' %}
          {%- elif 'temporali' in risk|lower %}
            {%- set icon = icon_temporali %}
            {%- set risk_type = 'temporali' %}
            {%- set abbr = 'TMP' %}
          {%- elif 'idrogeologico' in risk|lower %}
            {%- set icon = icon_idrogeologico %}
            {%- set risk_type = 'idrogeologico' %}
            {%- set abbr = 'IDG' %}
          {%- endif %}
          
          {%- set ns.parts = ns.parts + [abbr ~ level|string] %}
          {%- if level > ns.max_level %}
            {%- set ns.max_level = level %}
          {%- endif %}
          {%- if ns.first_icon == '' %}
            {%- set ns.first_icon = icon %}
          {%- endif %}
        {%- endif %}
      {%- endfor %}
    {%- endif %}
    
    {%- if ns.parts|length > 0 %}
      {%- set compact_text = ns.parts | join('-') %}
      
      {%- set payload = {
        'text': compact_text,
        'icon': ns.first_icon,
        'stack': false
      } %}
      
      {%- if rainbow_level == 0 or ns.max_level < rainbow_level %}
        {%- set payload = dict(payload, color=color_map[ns.max_level]) %}
      {%- endif %}
      
      {%- if rainbow_level > 0 and ns.max_level >= rainbow_level %}
        {%- set payload = dict(payload, rainbow=true) %}
      {%- endif %}
      
      {%- if enable_sound and ns.max_level >= sound_level %}
        {%- set payload = dict(payload, sound=sound_file) %}
      {%- endif %}
      
      {{ payload|tojson }}
    {%- else %}
      {}
    {%- endif %}

trigger:
  - platform: state
    entity_id: !input dpc_sensors
    id: alert_change

condition: []

action:
  # Send to custom app if mode is 'app' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['app', 'both'] }}"
    then:
      - repeat:
          for_each: "{{ devices_topics }}"
          sequence:
            # Remove previous app
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: ""

            # Publish compact app (if alerts present)
            - if:
                - condition: template
                  value_template: "{{ compact_payload != '{}' }}"
              then:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{ repeat.item }}"
                    payload: >-
                      {%- set payload_obj = compact_payload|from_json %}
                      {%- if message_duration > 0 %}
                        {%- set payload_obj = dict(payload_obj, duration=message_duration) %}
                      {%- endif %}
                      {{ payload_obj|tojson }}

  # Send AWTRIX notification if mode is 'notification' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['notification', 'both'] and compact_payload != '{}' }}"
    then:
      - repeat:
          for_each: "{{ notify_topics }}"
          sequence:
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: >-
                  {%- set payload_obj = compact_payload|from_json %}
                  {%- if notification_duration > 0 %}
                    {%- set payload_obj = dict(payload_obj, duration=notification_duration) %}
                  {%- else %}
                    {%- set payload_obj = dict(payload_obj, hold=true) %}
                  {%- endif %}
                  {{ payload_obj|tojson }}
