blueprint:
  name: "AWTRIX DPC Alert - Test Notification 🧪"
  description:
    "Sends a test notification to AWTRIX to verify the configuration.\n\n
    This blueprint creates an automation that can be manually triggered to send
    a test notification to AWTRIX devices.\n\n
    Useful to verify that icons and settings are correct."
  domain: automation
  input:
    awtrix:
      name: AWTRIX Device
      description: Select the AWTRIX devices for testing
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

    test_level:
      name: Test Level
      description: |
        Select the criticality level to test:
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 1
          max: 4
          mode: box
          step: 1
      default: 3

    message_duration:
      name: Message Duration ⏱️
      description: How long the message should remain on screen (in seconds)
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 20

    icon_test:
      name: Test Icon
      description: Icon ID to display in the test
      selector:
        text: {}
      default: "16754"

    enable_sound:
      name: Test with Sound 🔊
      description: Play a sound with the test notification
      selector:
        boolean: {}
      default: false

    sound_file:
      name: Sound File
      description: Audio file name to play (without extension)
      selector:
        text: {}
      default: "alarm"

    display_mode:
      name: Display Mode 📺
      description: |
        Choose how to display the test on AWTRIX:
        - Custom App: Persistent display until cleared
        - Notification: Temporary pop-up that auto-dismisses
        - Both: Send both custom app and notification
      selector:
        select:
          options:
            - label: "Custom App (Persistent)"
              value: "app"
            - label: "Notification (Temporary)"
              value: "notification"
            - label: "Both"
              value: "both"
      default: "notification"

mode: single

variables:
  device_ids: !input awtrix
  app_topic: "dpc_alert"
  test_level: !input test_level
  message_duration: !input message_duration
  icon_test: !input icon_test
  enable_sound: !input enable_sound
  sound_file: !input sound_file
  display_mode: !input display_mode

  devices_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/custom/' ~ app_topic] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  notify_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/notify'] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  color_map: |
    {{ dict({
      0: "#0080FF",
      1: "#00FF00",
      2: "#FFFF00",
      3: "#FF8000",
      4: "#FF0000"
    }) }}

  level_names: |
    {{ dict({
      1: "Ordinaria",
      2: "Moderata",
      3: "Elevata",
      4: "Estrema"
    }) }}

  test_payload: |
    {%- set alert_obj = {
      'icon': icon_test,
      'text': 'TEST DPC Alert - Livello ' ~ level_names[test_level],
      'duration': message_duration,
      'color': color_map[test_level],
      'pushIcon': 2,
      'repeat': 1
    } %}
    {%- if enable_sound %}
      {%- set _ = alert_obj.update({'sound': sound_file}) %}
    {%- endif %}
    {{ alert_obj|tojson }}

trigger: []

condition: []

action:
  # Send to custom app if mode is 'app' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['app', 'both'] }}"
    then:
      - repeat:
          for_each: "{{ devices_topics }}"
          sequence:
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: "{{ test_payload }}"

  # Send AWTRIX notification if mode is 'notification' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['notification', 'both'] }}"
    then:
      - repeat:
          for_each: "{{ notify_topics }}"
          sequence:
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: "{{ test_payload }}"

  - service: system_log.write
    data:
      message: "DPC Alert test notification sent to {{ devices_topics|length }} AWTRIX device(s) - Level {{ test_level }} - Mode: {{ display_mode }}"
      level: info
