blueprint:
  name: "AWTRIX DPC Alert - Test Notification ðŸ§ª"
  description:
    "Sends test notifications to AWTRIX devices to verify DPC alert configuration.\n\n
    This blueprint creates a manually-triggered automation for testing alert displays
    before real DPC alerts arrive. Essential for validating your setup.\n\n
    ## ðŸŽ¯ Purpose\n\n
    - Verify icons are correctly uploaded and display properly\n\n
    - Test different criticality levels (1-4) with accurate colors and effects\n\n
    - Test multiple simultaneous alerts (like real scenarios)\n\n
    - Test compact app display (e.g. \"IDR3-TMP4\") and detailed notifications\n\n
    - Validate sound notifications at different thresholds\n\n
    - Test both Custom App (persistent) and Notification (temporary) display modes\n\n
    - Confirm rainbow text effects work as configured\n\n
    - Ensure MQTT communication is functioning correctly\n\n\n
    ## ðŸ“ How to Use\n\n
    1. Create automation from this blueprint\n\n
    2. Select your AWTRIX device(s)\n\n
    3. Set test level for each risk type (0 = disabled, 1-4 = criticality level)\n\n
    4. Configure durations, effects, and display mode\n\n
    5. Save and trigger manually to send test notification(s)\n\n
    6. Verify display, colors, icons, sound, and effects\n\n
    7. Adjust settings as needed and test again\n\n\n
    ## âœ¨ Features\n\n
    - Test each risk type independently (hydraulic, storm, hydrogeological)\n\n
    - Test multiple alerts simultaneously\n\n
    - Compact app format: \"IDR3-TMP4\" (all alerts on one screen)\n\n
    - Detailed notification format: Full scrolling text (sent individually)\n\n
    - All 4 criticality levels with proper color coding\n\n
    - Configurable rainbow text effect (minimum level threshold)\n\n
    - Choose display mode: Custom App, Notification, or Both\n\n
    - Separate durations for custom apps and notifications\n\n
    - Hold mode support (notification duration = 0)\n\n
    - Optional sound notifications with level threshold\n\n
    - Test payload visible in trace for debugging"
  domain: automation
  input:
    awtrix:
      name: AWTRIX Device
      description: Select the AWTRIX devices for testing
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

    test_level_idraulico:
      name: Hydraulic Risk Test Level ðŸŒŠ
      description: |
        Criticality level for hydraulic risk test (0 = disabled):
        0 = Disabled (no test for this risk)
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    test_level_temporali:
      name: Storm Risk Test Level âš¡
      description: |
        Criticality level for storm risk test (0 = disabled):
        0 = Disabled (no test for this risk)
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 3

    test_level_idrogeologico:
      name: Hydrogeological Risk Test Level ðŸ”ï¸
      description: |
        Criticality level for hydrogeological risk test (0 = disabled):
        0 = Disabled (no test for this risk)
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    message_duration:
      name: Message Duration â±ï¸
      description: How long the message should remain on screen (in seconds). 0 = use global time
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 20

    notification_duration:
      name: Notification Duration ðŸ””
      description: How long the notification should remain visible (0 = hold until manual dismissal)
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 10

    icon_idraulico:
      name: Hydraulic Risk Icon
      description: "Icon for hydraulic risk (floods, overflows).\n
        Filename: dpc-idraulico (LaMetric ID: 63)"
      selector:
        text: {}
      default: "dpc-idraulico"

    icon_temporali:
      name: Storm Risk Icon
      description: "Icon for storm risk.\n
        Filename: dpc-temporali (LaMetric ID: 49299)"
      selector:
        text: {}
      default: "dpc-temporali"

    icon_idrogeologico:
      name: Hydrogeological Risk Icon
      description: "Icon for hydrogeological risk (landslides, mudslides).\n
        Filename: dpc-idrogeologico (LaMetric ID: 42639)"
      selector:
        text: {}
      default: "dpc-idrogeologico"

    icon_warning:
      name: Generic Alert Icon
      description: "Generic icon for other alert types.\n
        Filename: dpc-warning (LaMetric ID: 16754)"
      selector:
        text: {}
      default: "dpc-warning"

    enable_sound:
      name: Enable Sound ðŸ”Š
      description: Play a sound when an alert arrives
      selector:
        boolean: {}
      default: false

    sound_level:
      name: Minimum Level for Sound
      description: |
        Play sound only for alerts of this level or higher:
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 1
          max: 4
          mode: box
          step: 1
      default: 3

    sound_file:
      name: Sound File
      description: |
        Name of the audio file to play (without extension).
        Examples: alarm, doorbell, notification, etc.
        See the AWTRIX documentation for available sounds.
      selector:
        text: {}
      default: "alarm"

    rainbow_level:
      name: Minimum Level for Rainbow ðŸŒˆ
      description: |
        Display rainbow text for alerts of this level or higher (0 = disabled):
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    display_mode:
      name: Display Mode ðŸ“º
      description: |
        Choose how to display the test on AWTRIX:
        - Custom App: Persistent compact display (e.g. "IDR3-TMP4")
        - Notification: Temporary detailed pop-up with full text
        - Both: Persistent compact app + temporary detailed notification
      selector:
        select:
          options:
            - label: "Custom App (Persistent)"
              value: "app"
            - label: "Notification (Temporary)"
              value: "notification"
            - label: "Both"
              value: "both"
      default: "notification"

mode: single

variables:
  device_ids: !input awtrix
  app_topic: "dpc_alert"
  test_level_idraulico: !input test_level_idraulico
  test_level_temporali: !input test_level_temporali
  test_level_idrogeologico: !input test_level_idrogeologico
  message_duration: !input message_duration
  notification_duration: !input notification_duration
  icon_idraulico: !input icon_idraulico
  icon_temporali: !input icon_temporali
  icon_idrogeologico: !input icon_idrogeologico
  icon_warning: !input icon_warning
  enable_sound: !input enable_sound
  sound_level: !input sound_level
  sound_file: !input sound_file
  rainbow_level: !input rainbow_level
  display_mode: !input display_mode

  devices_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/custom/' ~ app_topic] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  notify_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/notify'] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  # Color map for criticality levels (same as main blueprint)
  color_map:
    0: "#0080FF"
    1: "#00FF00"
    2: "#FFFF00"
    3: "#FF6000"
    4: "#FF0000"

  # Criticality level names
  level_names:
    0: "None"
    1: "Ordinaria"
    2: "Moderata"
    3: "Elevata"
    4: "Estrema"

  # Risk type names
  risk_names:
    idraulico: "Idraulico"
    temporali: "Temporali"
    idrogeologico: "Idrogeologico"

  # Build compact payload for Custom App (single screen)
  app_payload: |
    {%- set ns = namespace(parts=[], max_level=0, first_icon='') %}
    
    {# Build compact text from active alerts #}
    {%- if test_level_idraulico > 0 %}
      {%- set ns.parts = ns.parts + ['IDR' ~ test_level_idraulico|string] %}
      {%- if test_level_idraulico > ns.max_level %}
        {%- set ns.max_level = test_level_idraulico %}
      {%- endif %}
      {%- if ns.first_icon == '' %}
        {%- set ns.first_icon = icon_idraulico %}
      {%- endif %}
    {%- endif %}
    
    {%- if test_level_temporali > 0 %}
      {%- set ns.parts = ns.parts + ['TMP' ~ test_level_temporali|string] %}
      {%- if test_level_temporali > ns.max_level %}
        {%- set ns.max_level = test_level_temporali %}
      {%- endif %}
      {%- if ns.first_icon == '' %}
        {%- set ns.first_icon = icon_temporali %}
      {%- endif %}
    {%- endif %}
    
    {%- if test_level_idrogeologico > 0 %}
      {%- set ns.parts = ns.parts + ['IDG' ~ test_level_idrogeologico|string] %}
      {%- if test_level_idrogeologico > ns.max_level %}
        {%- set ns.max_level = test_level_idrogeologico %}
      {%- endif %}
      {%- if ns.first_icon == '' %}
        {%- set ns.first_icon = icon_idrogeologico %}
      {%- endif %}
    {%- endif %}
    
    {%- if ns.parts|length > 0 %}
      {%- set compact_text = ns.parts | join('-') %}
      
      {%- set app_obj = {
        'text': compact_text,
        'icon': ns.first_icon,
        'stack': false
      } %}
      
      {%- if message_duration > 0 %}
        {%- set app_obj = dict(app_obj, duration=message_duration) %}
      {%- endif %}
      
      {%- if rainbow_level == 0 or ns.max_level < rainbow_level %}
        {%- set app_obj = dict(app_obj, color=color_map[ns.max_level]) %}
      {%- endif %}
      
      {%- if rainbow_level > 0 and ns.max_level >= rainbow_level %}
        {%- set app_obj = dict(app_obj, rainbow=true) %}
      {%- endif %}
      
      {%- if enable_sound and ns.max_level >= sound_level %}
        {%- set app_obj = dict(app_obj, sound=sound_file) %}
      {%- endif %}
      
      {{ app_obj|tojson }}
    {%- else %}
      {}
    {%- endif %}

  # Build notification payloads as list (will be sent individually)
  notification_list: |
    {%- set ns = namespace(notifs=[]) %}
    
    {%- if test_level_idraulico > 0 %}
      {%- set notif_obj = {
        'icon': icon_idraulico,
        'text': 'TEST Rischio Idraulico - Livello ' ~ level_names[test_level_idraulico],
        'stack': false
      } %}
      {%- if notification_duration > 0 %}
        {%- set notif_obj = dict(notif_obj, duration=notification_duration) %}
      {%- else %}
        {%- set notif_obj = dict(notif_obj, hold=true) %}
      {%- endif %}
      {%- if rainbow_level == 0 or test_level_idraulico < rainbow_level %}
        {%- set notif_obj = dict(notif_obj, color=color_map[test_level_idraulico]) %}
      {%- endif %}
      {%- if rainbow_level > 0 and test_level_idraulico >= rainbow_level %}
        {%- set notif_obj = dict(notif_obj, rainbow=true) %}
      {%- endif %}
      {%- if enable_sound and test_level_idraulico >= sound_level %}
        {%- set notif_obj = dict(notif_obj, sound=sound_file) %}
      {%- endif %}
      {%- set ns.notifs = ns.notifs + [notif_obj] %}
    {%- endif %}
    
    {%- if test_level_temporali > 0 %}
      {%- set notif_obj = {
        'icon': icon_temporali,
        'text': 'TEST Rischio Temporali - Livello ' ~ level_names[test_level_temporali],
        'stack': false
      } %}
      {%- if notification_duration > 0 %}
        {%- set notif_obj = dict(notif_obj, duration=notification_duration) %}
      {%- else %}
        {%- set notif_obj = dict(notif_obj, hold=true) %}
      {%- endif %}
      {%- if rainbow_level == 0 or test_level_temporali < rainbow_level %}
        {%- set notif_obj = dict(notif_obj, color=color_map[test_level_temporali]) %}
      {%- endif %}
      {%- if rainbow_level > 0 and test_level_temporali >= rainbow_level %}
        {%- set notif_obj = dict(notif_obj, rainbow=true) %}
      {%- endif %}
      {%- if enable_sound and test_level_temporali >= sound_level %}
        {%- set notif_obj = dict(notif_obj, sound=sound_file) %}
      {%- endif %}
      {%- set ns.notifs = ns.notifs + [notif_obj] %}
    {%- endif %}
    
    {%- if test_level_idrogeologico > 0 %}
      {%- set notif_obj = {
        'icon': icon_idrogeologico,
        'text': 'TEST Rischio Idrogeologico - Livello ' ~ level_names[test_level_idrogeologico],
        'stack': false
      } %}
      {%- if notification_duration > 0 %}
        {%- set notif_obj = dict(notif_obj, duration=notification_duration) %}
      {%- else %}
        {%- set notif_obj = dict(notif_obj, hold=true) %}
      {%- endif %}
      {%- if rainbow_level == 0 or test_level_idrogeologico < rainbow_level %}
        {%- set notif_obj = dict(notif_obj, color=color_map[test_level_idrogeologico]) %}
      {%- endif %}
      {%- if rainbow_level > 0 and test_level_idrogeologico >= rainbow_level %}
        {%- set notif_obj = dict(notif_obj, rainbow=true) %}
      {%- endif %}
      {%- if enable_sound and test_level_idrogeologico >= sound_level %}
        {%- set notif_obj = dict(notif_obj, sound=sound_file) %}
      {%- endif %}
      {%- set ns.notifs = ns.notifs + [notif_obj] %}
    {%- endif %}
    
    {{ ns.notifs }}

trigger: []

condition: []

action:
  # Send to custom app if mode is 'app' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['app', 'both'] }}"
    then:
      - repeat:
          for_each: "{{ devices_topics }}"
          sequence:
            # Remove previous app
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: ""

            # Publish compact app (if alerts present)
            - if:
                - condition: template
                  value_template: "{{ app_payload != '{}' }}"
              then:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{ repeat.item }}"
                    payload: "{{ app_payload }}"

  # Send AWTRIX notifications if mode is 'notification' or 'both'
  # Notifications must be sent individually, not as array
  - if:
      - condition: template
        value_template: "{{ display_mode in ['notification', 'both'] and notification_list|length > 0 }}"
    then:
      - repeat:
          for_each: "{{ notify_topics }}"
          sequence:
            # Send each notification individually
            - repeat:
                for_each: "{{ notification_list }}"
                sequence:
                  - service: mqtt.publish
                    data:
                      qos: 0
                      retain: false
                      topic: "{{ notify_topics[0] }}"
                      payload: "{{ repeat.item|tojson }}"
                  # Small delay between notifications
                  - delay:
                      milliseconds: 100

  - service: system_log.write
    data:
      message: "DPC Alert test notification sent to {{ devices_topics|length }} AWTRIX device(s) - Mode: {{ display_mode }}"
      level: info
