blueprint:
  name: "AWTRIX Civil Protection Alert ðŸ‡®ðŸ‡¹"
  description:
    "Display Italian Civil Protection (Protezione Civile) weather alerts on your AWTRIX LED matrix device.\n\n
    Automatically monitors DPC alert sensors and displays color-coded notifications with icons,
    sound alerts, and visual effects based on criticality level.\n\n
    ## âš ï¸ REQUIREMENTS\n
    - **Home Assistant** 2024.6.0 or newer\n
    - **AWTRIX 3** device configured with MQTT\n
    - **[DPC Alert Integration](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert)** installed and configured\n\n
    ## ðŸŽ¯ KEY FEATURES\n
    - **Multi-sensor monitoring**: Track multiple DPC sensors simultaneously\n
    - **Criticality filtering**: Show only alerts above configurable threshold (0-4)\n
    - **Automatic color coding**: Vivid colors based on alert level (Blue/Green/Yellow/Orange/Red)\n
    - **Rainbow text effect**: Optional colorful animation for high-severity alerts\n
    - **Ripple background effect**: Animated ripple for critical warnings (configurable threshold)\n
    - **Sound notifications**: Optional audio alerts with minimum level threshold\n
    - **Flexible display modes**: Choose Custom App (persistent), Notification (temporary), or Both\n
    - **Auto-clear**: Removes alerts automatically when no longer active\n
    - **Multi-device support**: Send to multiple AWTRIX devices simultaneously\n\n
    ## ðŸ“¦ RECOMMENDED ICONS\n
    Upload these icons to your AWTRIX for best results:\n
    - `dpc-idraulico` (63) - Hydraulic risk (floods, overflows)\n
    - `dpc-temporali` (49299) - Thunderstorm risk (lightning, strong winds)\n
    - `dpc-idrogeologico` (42639) - Hydrogeological risk (landslides, mudflows)\n
    - `dpc-warning` (16754) - Generic alert icon (fallback)\n\n
    Get icons from [LaMetric Icons](https://developer.lametric.com/icons) or create custom GIF files.\n
    See [Icons Upload Guide](https://github.com/Raythekool/ha-awtrix-dpc-alert/blob/main/ICONS_UPLOAD.md) for automated upload script.\n\n
    ## âš™ï¸ CONFIGURATION OPTIONS\n
    - **Alert Level Threshold**: Filter by minimum criticality (0-4)\n
    - **Display Durations**: Separate controls for custom apps and notifications\n
    - **Rainbow Text Level**: Enable rainbow animation at specified level (0=disabled)\n
    - **Ripple Effect Level**: Enable ripple background at specified level (default: 3)\n
    - **Sound Settings**: Optional audio with minimum level threshold\n
    - **Display Mode**: Custom App (stays visible), Notification (temporary pop-up), or Both\n
    - **Custom Icons**: Override default icon names for each risk type\n\n
    ## ðŸ”— MORE INFO\n
    Documentation: https://github.com/Raythekool/ha-awtrix-dpc-alert\n
    Updates: https://github.com/Raythekool/ha-awtrix-dpc-alert/blob/main/awtrix_dpc_alert.yaml"
  domain: automation
  homeassistant:
    min_version: "2024.6.0"
  source_url: https://github.com/Raythekool/awtrix_dpc_alert/blob/main/awtrix_dpc_alert.yaml
  input:
    awtrix:
      name: AWTRIX Device
      description: Select your AWTRIX device
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

    dpc_sensors:
      name: DPC Alert Sensors
      description: Select the alert sensors you want to monitor
      selector:
        entity:
          filter:
            - domain: binary_sensor
              integration: dpc
          multiple: true

    warning_level:
      name: Minimum Alert Level
      description: |
        0 = Show all alerts (including no criticality)
        1 = Green (Ordinary criticality)
        2 = Yellow (Moderate criticality)
        3 = Orange (High criticality)
        4 = Red (Extreme criticality)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 1

    message_duration:
      name: Message Duration â±ï¸
      description: How long the message should stay on screen (in seconds). 0 = use global time
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 20

    notification_duration:
      name: Notification Duration ðŸ””
      description: How long the notification should remain visible (0 = hold until manual dismissal)
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 0

    icon_idraulico:
      name: Hydraulic Risk Icon
      description: "Icon for hydraulic risk (floods, overflows).\n
        Filename: dpc-idraulico (LaMetric ID: 63)"
      selector:
        text: {}
      default: "dpc-idraulico"

    icon_temporali:
      name: Storm Risk Icon
      description: "Icon for storm risk.\n
        Filename: dpc-temporali (LaMetric ID: 49299)"
      selector:
        text: {}
      default: "dpc-temporali"

    icon_idrogeologico:
      name: Hydrogeological Risk Icon
      description: "Icon for hydrogeological risk (landslides, mudslides).\n
        Filename: dpc-idrogeologico (LaMetric ID: 42639)"
      selector:
        text: {}
      default: "dpc-idrogeologico"

    icon_warning:
      name: Generic Alert Icon
      description: "Generic icon for other alert types.\n
        Filename: dpc-warning (LaMetric ID: 16754)"
      selector:
        text: {}
      default: "dpc-warning"

    enable_sound:
      name: Enable Sound ðŸ”Š
      description: Play a sound when an alert arrives
      selector:
        boolean: {}
      default: false

    sound_level:
      name: Minimum Level for Sound
      description: |
        Play sound only for alerts of this level or higher:
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 1
          max: 4
          mode: box
          step: 1
      default: 3

    sound_file:
      name: Sound File
      description: |
        Name of the audio file to play (without extension).
        Examples: alarm, doorbell, notification, etc.
        See the AWTRIX documentation for available sounds.
      selector:
        text: {}
      default: "alarm"

    rainbow_level:
      name: Minimum Level for Rainbow ðŸŒˆ
      description: |
        Display rainbow text for alerts of this level or higher (0 = disabled):
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    ripple_level:
      name: Minimum Level for Ripple Effect ã€°ï¸
      description: |
        Show ripple effect for alerts of this level or higher (0 = disabled):
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 3

    display_mode:
      name: Display Mode ðŸ“º
      description: |
        Choose how to display alerts on AWTRIX:
        - Custom App: Persistent display until cleared
        - Notification: Temporary pop-up that auto-dismisses
        - Both: Send both custom app and notification
      selector:
        select:
          options:
            - label: "Custom App (Persistent)"
              value: "app"
            - label: "Notification (Temporary)"
              value: "notification"
            - label: "Both"
              value: "both"
      default: "app"

mode: restart

variables:
  device_ids: !input awtrix
  app_topic: "dpc_alert"
  devices_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/custom/' ~ app_topic] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  notify_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/notify'] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  dpc_sensors: !input dpc_sensors
  warning_level: !input warning_level
  message_duration: !input message_duration
  notification_duration: !input notification_duration
  icon_idraulico: !input icon_idraulico
  icon_temporali: !input icon_temporali
  icon_idrogeologico: !input icon_idrogeologico
  icon_warning: !input icon_warning
  enable_sound: !input enable_sound
  sound_level: !input sound_level
  sound_file: !input sound_file
  rainbow_level: !input rainbow_level
  ripple_level: !input ripple_level
  display_mode: !input display_mode

  # Color map for criticality levels
  color_map:
    0: "#0080FF"
    1: "#00FF00"
    2: "#FFFF00"
    3: "#FF6000"
    4: "#FF0000"

  # Criticality level names
  level_names:
    0: "None"
    1: "Ordinary"
    2: "Moderate"
    3: "High"
    4: "Extreme"

  # Build payload with all active alerts
  alerts: |
    {%- set ns = namespace(alerts=[]) %}
    {%- for sensor in dpc_sensors %}
      {%- if is_state(sensor, 'on') and state_attr(sensor, 'level')|int(0) >= warning_level %}
        {%- set level = state_attr(sensor, 'level')|int(0) %}
        {%- set alert = state_attr(sensor, 'alert') %}
        {%- set risk = state_attr(sensor, 'risk') %}
        {%- set zone = state_attr(sensor, 'zone_name') %}
        {%- set expires = state_attr(sensor, 'expires') %}
        
        {%- set icon = icon_warning %}
        {%- if 'idraulico' in risk|lower %}
          {%- set icon = icon_idraulico %}
        {%- elif 'temporali' in risk|lower %}
          {%- set icon = icon_temporali %}
        {%- elif 'idrogeologico' in risk|lower %}
          {%- set icon = icon_idrogeologico %}
        {%- endif %}
        
        {%- set duration_value = message_duration if display_mode == 'app' else notification_duration %}
        {%- set alert_obj = {
          'icon': icon,
          'text': alert ~ ' - ' ~ zone,
          'duration': duration_value,
          'stack': false,
          'overlay': 'clear'
        } %}
        {#- Only set color if rainbow is not active -#}
        {%- if rainbow_level == 0 or level < rainbow_level %}
          {%- set alert_obj = dict(alert_obj, color=color_map[level]) %}
        {%- endif %}
        {%- if rainbow_level > 0 and level >= rainbow_level %}
          {%- set alert_obj = dict(alert_obj, rainbow=true) %}
        {%- endif %}
        {%- if ripple_level > 0 and level >= ripple_level %}
          {%- set alert_obj = dict(alert_obj, effect='Ripple') %}
        {%- endif %}
        {%- if enable_sound and level >= sound_level %}
          {%- set alert_obj = dict(alert_obj, sound=sound_file) %}
        {%- endif %}
        {%- if display_mode in ['notification', 'both'] and notification_duration == 0 %}
          {%- set alert_obj = dict(alert_obj, hold=true) %}
        {%- endif %}
        {%- set ns.alerts = ns.alerts + [alert_obj] %}
      {%- endif %}
    {%- endfor %}
    {{ ns.alerts }}

  payload: |
    {%- set alert_list = alerts %}
    {%- if alert_list|length > 0 %}
      {%- if alert_list|length == 1 %}
        {{ alert_list[0]|tojson }}
      {%- else %}
        {{ alert_list|tojson }}
      {%- endif %}
    {%- else %}
      {}
    {%- endif %}

trigger:
  - platform: state
    entity_id: !input dpc_sensors
    id: alert_change

condition: []

action:
  # Send to custom app if mode is 'app' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['app', 'both'] }}"
    then:
      - repeat:
          for_each: "{{ devices_topics }}"
          sequence:
            # Remove previous app
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: ""

            # Publish new alerts (if present)
            - if:
                - condition: template
                  value_template: "{{ alerts|length > 0 }}"
              then:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{ repeat.item }}"
                    payload: "{{ payload }}"

  # Send AWTRIX notification if mode is 'notification' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['notification', 'both'] and alerts|length > 0 }}"
    then:
      - repeat:
          for_each: "{{ notify_topics }}"
          sequence:
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: "{{ payload }}"
