blueprint:
  name: "AWTRIX Civil Protection Alert ðŸ‡®ðŸ‡¹"
  description:
    "Display Italian Civil Protection (Protezione Civile) weather alerts on your AWTRIX LED matrix device.\n\n
    Automatically monitors DPC alert sensors and displays color-coded notifications with icons,
    sound alerts, and visual effects based on criticality level.\n\n
    ## âš ï¸ REQUIREMENTS\n
    - **Home Assistant** 2024.6.0 or newer\n
    - **AWTRIX 3** device configured with MQTT\n
    - **[DPC Alert Integration](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert)** installed and configured\n\n
    ## ðŸŽ¯ KEY FEATURES\n
    - **Multi-sensor monitoring**: Track multiple DPC sensors simultaneously\n
    - **Criticality filtering**: Show only alerts above configurable threshold (0-4)\n
    - **Automatic color coding**: Vivid colors based on alert level (Blue/Green/Yellow/Orange/Red)\n
    - **Compact display format**: Shows abbreviated alerts (e.g. \"idro3-temporali4\") for apps\n
    - **Full name notifications**: Triggered sensor shows full alert name in notifications\n
    - **Rainbow text effect**: Optional colorful animation for high-severity alerts\n
    - **Sound notifications**: Optional audio alerts with minimum level threshold\n
    - **Flexible display modes**: Choose Custom App (persistent), Notification (temporary), or Both\n
    - **Auto-clear**: Removes alerts automatically when no longer active\n
    - **Multi-device support**: Send to multiple AWTRIX devices simultaneously\n
    - **Test mode**: Manually trigger test alerts without waiting for real DPC data\n\n
    ## ðŸ“º DISPLAY FORMAT\n
    - **Custom App**: Compact format with all alerts (e.g. \"idro3-temporali4\")\n
    - **Notification**: Full name of triggered alert only (e.g. \"Allerta Idraulico - Toscana\")\n
    - **idro** = Rischio Idraulico (Hydraulic)\n
    - **temporali** = Rischio Temporali (Storm)\n
    - **idrogeo** = Rischio Idrogeologico (Hydrogeological)\n
    - Number = criticality level (1-4)\n
    Color is based on highest alert level present.\n\n
    ## ðŸ“¦ RECOMMENDED ICON\n
    Upload this icon to your AWTRIX for best results:\n
    - `dpc-warning` (16754) - Alert icon for all risk types\n\n
    Get the icon from [LaMetric Icons](https://developer.lametric.com/icons) or create a custom GIF file.\n
    See [Icons Upload Guide](https://github.com/Raythekool/ha-awtrix-dpc-alert/blob/main/ICONS_UPLOAD.md) for automated upload script.\n\n
    ## âš™ï¸ CONFIGURATION OPTIONS\n
    - **Alert Level Threshold**: Filter by minimum criticality (0-4)\n
    - **Repeat Count**: Number of times to show the custom app\n
    - **Notification Duration**: How long notifications stay visible\n
    - **Rainbow Text Level**: Enable rainbow animation at specified level (0=disabled)\n
    - **Sound Settings**: Optional audio with minimum level threshold\n
    - **Display Mode**: Custom App (stays visible), Notification (temporary pop-up), or Both\n
    - **Custom Icon**: Override default icon name\n
    - **Test Mode**: Enable manual testing with configurable alert levels\n\n
    ## ðŸ”— MORE INFO\n
    Documentation: https://github.com/Raythekool/ha-awtrix-dpc-alert\n
    Updates: https://github.com/Raythekool/ha-awtrix-dpc-alert/blob/main/awtrix_dpc_alert.yaml"
  domain: automation
  homeassistant:
    min_version: "2024.6.0"
  source_url: https://github.com/Raythekool/awtrix_dpc_alert/blob/main/awtrix_dpc_alert.yaml
  input:
    awtrix:
      name: AWTRIX Device
      description: Select your AWTRIX device
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

    dpc_sensors:
      name: DPC Alert Sensors
      description: Select the alert sensors you want to monitor
      selector:
        entity:
          filter:
            - domain: binary_sensor
              integration: dpc
          multiple: true

    warning_level:
      name: Minimum Alert Level
      description: |
        0 = Show all alerts (including no criticality)
        1 = Green (Ordinary criticality)
        2 = Yellow (Moderate criticality)
        3 = Orange (High criticality)
        4 = Red (Extreme criticality)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 1

    repeat_count:
      name: Repeat Count ðŸ”
      description: Number of times to display the custom app (0 = display once without repeat)
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
      default: 5

    notification_duration:
      name: Notification Duration ðŸ””
      description: How long the notification should remain visible (0 = hold until manual dismissal)
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: sec
          step: 1
          mode: slider
      default: 10

    icon_warning:
      name: Alert Icon
      description: "Icon for all alert types.\n
        Filename: dpc-warning (LaMetric ID: 16754)"
      selector:
        text: {}
      default: "dpc-warning"

    enable_sound:
      name: Enable Sound ðŸ”Š
      description: Play a sound when an alert arrives
      selector:
        boolean: {}
      default: false

    sound_level:
      name: Minimum Level for Sound
      description: |
        Play sound only for alerts of this level or higher:
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 1
          max: 4
          mode: box
          step: 1
      default: 3

    sound_file:
      name: Sound File
      description: |
        Name of the audio file to play (without extension).
        Examples: alarm, doorbell, notification, etc.
        See the AWTRIX documentation for available sounds.
      selector:
        text: {}
      default: "alarm"

    rainbow_level:
      name: Minimum Level for Rainbow ðŸŒˆ
      description: |
        Display rainbow text for alerts of this level or higher (0 = disabled):
        1 = Green (Ordinary)
        2 = Yellow (Moderate)
        3 = Orange (High)
        4 = Red (Extreme)
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    display_mode:
      name: Display Mode ðŸ“º
      description: |
        Choose how to display alerts on AWTRIX:
        - Custom App: Persistent compact display (e.g. "idro3-temporali4")
        - Notification: Temporary pop-up with full alert name
        - Both: Persistent app + temporary notification
      selector:
        select:
          options:
            - label: "Custom App (Persistent)"
              value: "app"
            - label: "Notification (Temporary)"
              value: "notification"
            - label: "Both"
              value: "both"
      default: "app"

    # TEST MODE INPUTS
    enable_test_mode:
      name: Enable Test Mode ðŸ§ª
      description: |
        Enable test mode to manually trigger alerts.
        When enabled, automation ignores DPC sensors and uses test levels instead.
        Perfect for verifying icon, colors, and display settings.
      selector:
        boolean: {}
      default: false

    test_level_idraulico:
      name: "[TEST] Hydraulic Risk Level ðŸŒŠ"
      description: "Test level for hydraulic risk (0 = disabled, 1-4 = criticality)"
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    test_level_temporali:
      name: "[TEST] Storm Risk Level âš¡"
      description: "Test level for storm risk (0 = disabled, 1-4 = criticality)"
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

    test_level_idrogeologico:
      name: "[TEST] Hydrogeological Risk Level ðŸ”ï¸"
      description: "Test level for hydrogeological risk (0 = disabled, 1-4 = criticality)"
      selector:
        number:
          min: 0
          max: 4
          mode: box
          step: 1
      default: 0

mode: restart

variables:
  device_ids: !input awtrix
  app_topic: "dpc_alert"
  devices_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/custom/' ~ app_topic] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  notify_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/notify'] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  dpc_sensors: !input dpc_sensors
  warning_level: !input warning_level
  repeat_count: !input repeat_count
  notification_duration: !input notification_duration
  icon_warning: !input icon_warning
  enable_sound: !input enable_sound
  sound_level: !input sound_level
  sound_file: !input sound_file
  rainbow_level: !input rainbow_level
  display_mode: !input display_mode
  enable_test_mode: !input enable_test_mode
  test_level_idraulico: !input test_level_idraulico
  test_level_temporali: !input test_level_temporali
  test_level_idrogeologico: !input test_level_idrogeologico

  # Color map for criticality levels
  color_map:
    0: "#0080FF"
    1: "#00FF00"
    2: "#FFFF00"
    3: "#FF6000"
    4: "#FF0000"

  # Criticality level names
  level_names:
    0: "None"
    1: "Ordinaria"
    2: "Moderata"
    3: "Elevata"
    4: "Estrema"

  # Risk abbreviations for compact display (longer names)
  risk_abbr:
    idraulico: "idro"
    temporali: "temporali"
    idrogeologico: "idrogeo"

  # Unified compact payload for custom app
  compact_payload: |
    {%- set ns = namespace(parts=[], max_level=0) %}
    {%- set test_prefix = '' %}
    
    {%- if enable_test_mode %}
      {%- set test_prefix = 'TEST ' %}
      {# TEST MODE: Use test levels #}
      {%- if test_level_idraulico > 0 %}
        {%- set ns.parts = ns.parts + ['idro' ~ test_level_idraulico|string] %}
        {%- if test_level_idraulico > ns.max_level %}
          {%- set ns.max_level = test_level_idraulico %}
        {%- endif %}
      {%- endif %}
      
      {%- if test_level_temporali > 0 %}
        {%- set ns.parts = ns.parts + ['temporali' ~ test_level_temporali|string] %}
        {%- if test_level_temporali > ns.max_level %}
          {%- set ns.max_level = test_level_temporali %}
        {%- endif %}
      {%- endif %}
      
      {%- if test_level_idrogeologico > 0 %}
        {%- set ns.parts = ns.parts + ['idrogeo' ~ test_level_idrogeologico|string] %}
        {%- if test_level_idrogeologico > ns.max_level %}
          {%- set ns.max_level = test_level_idrogeologico %}
        {%- endif %}
      {%- endif %}
    {%- else %}
      {# REAL MODE: Use DPC sensors #}
      {%- for sensor in dpc_sensors %}
        {%- if is_state(sensor, 'on') and state_attr(sensor, 'level')|int(0) >= warning_level %}
          {%- set level = state_attr(sensor, 'level')|int(0) %}
          {%- set risk = state_attr(sensor, 'risk') %}
          
          {%- set abbr = 'alert' %}
          
          {%- if 'idraulico' in risk|lower %}
            {%- set abbr = 'idro' %}
          {%- elif 'temporali' in risk|lower %}
            {%- set abbr = 'temporali' %}
          {%- elif 'idrogeologico' in risk|lower %}
            {%- set abbr = 'idrogeo' %}
          {%- endif %}
          
          {%- set ns.parts = ns.parts + [abbr ~ level|string] %}
          {%- if level > ns.max_level %}
            {%- set ns.max_level = level %}
          {%- endif %}
        {%- endif %}
      {%- endfor %}
    {%- endif %}
    
    {%- if ns.parts|length > 0 %}
      {%- set compact_text = test_prefix ~ ns.parts | join('-') %}
      
      {%- set payload = {
        'text': compact_text,
        'icon': icon_warning,
        'stack': false
      } %}
      
      {%- if repeat_count > 0 %}
        {%- set payload = dict(payload, repeat=repeat_count) %}
      {%- endif %}
      
      {%- if rainbow_level == 0 or ns.max_level < rainbow_level %}
        {%- set payload = dict(payload, color=color_map[ns.max_level]) %}
      {%- endif %}
      
      {%- if rainbow_level > 0 and ns.max_level >= rainbow_level %}
        {%- set payload = dict(payload, rainbow=true) %}
      {%- endif %}
      
      {%- if enable_sound and ns.max_level >= sound_level %}
        {%- set payload = dict(payload, sound=sound_file) %}
      {%- endif %}
      
      {{ payload|tojson }}
    {%- else %}
      {}
    {%- endif %}

  # Notification payload - only triggered sensor with full name
  notification_payload: |
    {%- set triggered = trigger.entity_id if trigger is defined and trigger.entity_id is defined else '' %}
    
    {%- if enable_test_mode %}
      {# TEST MODE: Show test notification #}
      {%- set test_alerts = [] %}
      {%- if test_level_idraulico > 0 %}
        {%- set test_alerts = test_alerts + [{'text': 'TEST Allerta Idraulico Livello ' ~ test_level_idraulico, 'level': test_level_idraulico}] %}
      {%- endif %}
      {%- if test_level_temporali > 0 %}
        {%- set test_alerts = test_alerts + [{'text': 'TEST Allerta Temporali Livello ' ~ test_level_temporali, 'level': test_level_temporali}] %}
      {%- endif %}
      {%- if test_level_idrogeologico > 0 %}
        {%- set test_alerts = test_alerts + [{'text': 'TEST Allerta Idrogeologico Livello ' ~ test_level_idrogeologico, 'level': test_level_idrogeologico}] %}
      {%- endif %}
      
      {%- if test_alerts|length > 0 %}
        {%- set alert = test_alerts[0] %}
        {%- set payload = {
          'text': alert.text,
          'icon': icon_warning,
          'stack': false
        } %}
        
        {%- if notification_duration > 0 %}
          {%- set payload = dict(payload, duration=notification_duration) %}
        {%- else %}
          {%- set payload = dict(payload, hold=true) %}
        {%- endif %}
        
        {%- if rainbow_level == 0 or alert.level < rainbow_level %}
          {%- set payload = dict(payload, color=color_map[alert.level]) %}
        {%- endif %}
        
        {%- if rainbow_level > 0 and alert.level >= rainbow_level %}
          {%- set payload = dict(payload, rainbow=true) %}
        {%- endif %}
        
        {%- if enable_sound and alert.level >= sound_level %}
          {%- set payload = dict(payload, sound=sound_file) %}
        {%- endif %}
        
        {{ payload|tojson }}
      {%- else %}
        {}
      {%- endif %}
    {%- elif triggered and is_state(triggered, 'on') and state_attr(triggered, 'level')|int(0) >= warning_level %}
      {# REAL MODE: Show triggered sensor only #}
      {%- set level = state_attr(triggered, 'level')|int(0) %}
      {%- set alert_text = state_attr(triggered, 'alert') %}
      {%- set risk = state_attr(triggered, 'risk') %}
      
      {%- set full_text = alert_text ~ ' - ' ~ risk %}
      
      {%- set payload = {
        'text': full_text,
        'icon': icon_warning,
        'stack': false
      } %}
      
      {%- if notification_duration > 0 %}
        {%- set payload = dict(payload, duration=notification_duration) %}
      {%- else %}
        {%- set payload = dict(payload, hold=true) %}
      {%- endif %}
      
      {%- if rainbow_level == 0 or level < rainbow_level %}
        {%- set payload = dict(payload, color=color_map[level]) %}
      {%- endif %}
      
      {%- if rainbow_level > 0 and level >= rainbow_level %}
        {%- set payload = dict(payload, rainbow=true) %}
      {%- endif %}
      
      {%- if enable_sound and level >= sound_level %}
        {%- set payload = dict(payload, sound=sound_file) %}
      {%- endif %}
      
      {{ payload|tojson }}
    {%- else %}
      {}
    {%- endif %}

trigger:
  - platform: state
    entity_id: !input dpc_sensors
    id: alert_change

condition: []

action:
  # Send to custom app if mode is 'app' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['app', 'both'] }}"
    then:
      - repeat:
          for_each: "{{ devices_topics }}"
          sequence:
            # Remove previous app
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: ""

            # Publish compact app (if alerts present)
            - if:
                - condition: template
                  value_template: "{{ compact_payload != '{}' }}"
              then:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{ repeat.item }}"
                    payload: "{{ compact_payload }}"

  # Send AWTRIX notification if mode is 'notification' or 'both'
  - if:
      - condition: template
        value_template: "{{ display_mode in ['notification', 'both'] and notification_payload != '{}' }}"
    then:
      - repeat:
          for_each: "{{ notify_topics }}"
          sequence:
            - service: mqtt.publish
              data:
                qos: 0
                retain: false
                topic: "{{ repeat.item }}"
                payload: "{{ notification_payload }}"
